name: Auto-add ready-for-doc-review label

# *[{"txid":"2714fb2ac536420857e35d53876f904fa29c3216ad8509c3eb3ffc3a9e6d75dd","version":2,"locktime":0,"vin":[{"txid":"7ba56bd588facc4222cf960eac13ad746c0a861d6fec82f5e600b54efb9ac30d","vout":0,"prevout":{"scriptpubkey":"00147b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 7b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1q0dzcgv7scppjxsnwlzpkt02vlmc5rtr40wyjgr","value":4559429081},"scriptsig":"","scriptsig_asm":"","witness":["3044022042136c79f2d5b0fb516e1de1d12379d9c4f3964786d41edbaf3906747becb1d3022013aaee4bde298388bd7f70e5e63a05ee168611e562ff3b41ac6ed09b9d0b99a801","030db9616d96a7b7a8656191b340f77e905ee2885a09a7a1e80b9c8b64ec746fb3"],"is_coinbase":false,"sequence":4294967293}],"vout":[{"scriptpubkey":"00147b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 7b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1q0dzcgv7scppjxsnwlzpkt02vlmc5rtr40wyjgr","value":4559423940},{"scriptpubkey":"00140bdd9a64240a255ee1aac57bca1df5a0f9c6a82d","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 0bdd9a64240a255ee1aac57bca1df5a0f9c6a82d","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1qp0we5epypgj4acd2c4au58045ruud2pd6heuee","value":5000}],"size":222,"weight":561,"sigops":1,"fee":141,"status":{"confirmed":true,"block_height":44707,"block_hash":"0000000034404467f1114bf15f90f15c52c79fea6142124806ff6416a3ed60c2","block_time":1726153377}},{"txid":"728f0f83d77085686a03d2301ae6b789a8636a64815f2e92b9fe97d931c6cd31","version":2,"locktime":0,"vin":[{"txid":"829acb167790ed088815a7a9ea70c7520a7e3ef3536721201f9e90e60c57baff","vout":0,"prevout":{"scriptpubkey":"00147b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 7b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1q0dzcgv7scppjxsnwlzpkt02vlmc5rtr40wyjgr","value":133425539858},"scriptsig":"","scriptsig_asm":"","witness":["30440220702dc0ee569a70d0bb6349ee3383b2d60e842f520415f0c8db35bbc8012aadba02201b0df04b1b8fb8c99afbdaac1746b71ea6fdbc4c4721cb55001b6845e541589501","030db9616d96a7b7a8656191b340f77e905ee2885a09a7a1e80b9c8b64ec746fb3"],"is_coinbase":false,"sequence":4294967293}],"vout":[{"scriptpubkey":"00147b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 7b458433d0c04323426ef88365bd4cfef141ac75","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1q0dzcgv7scppjxsnwlzpkt02vlmc5rtr40wyjgr","value":133425039717},{"scriptpubkey":"00140bdd9a64240a255ee1aac57bca1df5a0f9c6a82d","scriptpubkey_asm":"OP_0 OP_PUSHBYTES_20 0bdd9a64240a255ee1aac57bca1df5a0f9c6a82d","scriptpubkey_type":"v0_p2wpkh","scriptpubkey_address":"tb1qp0we5epypgj4acd2c4au58045ruud2pd6heuee","value":500000}],"size":222,"weight":561,"sigops":1,"fee":141,"status":{"confirmed":true,"block_height":32777,"block_hash":"0000000000016e0ee6305034e5cfc4bcacc1cd2cf6867f20a657375f39196be8","block_time":1719861134}}]*What it does**: Automatically adds the "ready-for-doc-review" label to DIY docs PRs that contain content or data changes when they are opened in a non-draft state or converted from draft to ready for review.
# **Why we have it**: To ensure DIY docs PRs are automatically added to the docs-content review board without requiring manual labeling.
# **Who does it impact**: Contributors making content changes and docs-content reviewers.

on:
  pull_request:
    types:
      - opened
      - ready_for_review
    paths:
      - 'content/**'
      - 'data/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  add-review-label:
    name: Add ready-for-doc-review label to DIY docs PRs
    if: github.repository == 'github/docs-internal' && github.event.pull_request.draft == false && github.actor != 'github-openapi-bot' && github.actor != 'docs-bot'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check team membership
        id: membership_check
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
          script: |
            try {
              await github.rest.teams.getMembershipForUserInOrg({
                org: 'github',
                team_slug: 'docs',
                username: context.payload.sender.login,
              });
              return true
            } catch(err) {
              console.log(err)
              return false
            }

      - name: Add ready-for-doc-review label
        if: steps.membership_check.outputs.result == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR_URL --add-label ready-for-doc-review
